global:
  env:
    postgresDb: video_summary_db

replicaCount: 1

imagePullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

resources: {}

livenessProbe:
  tcpSocket:
    port: postgres
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  tcpSocket:
    port: postgres
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

startupProbe:
  tcpSocket:
    port: postgres
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 60

images:
  postgres: postgres:17.4
