{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-broker.fullname" . }}
  labels:
    {{- include "mqtt-broker.labels" . | nindent 4 }}
    app.kubernetes.io/component: mqtt-broker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mqtt-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mqtt-broker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mqtt-broker
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "lvc.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mqtt-broker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: mqtt
              containerPort: {{ .Values.config.listener }}
              protocol: TCP
          env:
            {{- include "lvc.proxyEnv" . | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: mqtt
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mosquitto-config
          configMap:
            name: {{ include "mqtt-broker.fullname" . }}-config
