# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.05
      y: 0.05
    scale_linear_turbo:
      x: 0.5
      y: 0.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 1.5
    
    enable_button: 5
    enable_turbo_button: 7
      
# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux:
  ros__parameters:
    topics:
      joystick:
        topic   : joy_vel
        timeout : 1.0
        priority: 100
      keyboard:
        topic   : key_vel
        timeout : 0.5
        priority: 60
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 40
    # locks:
    #   pause:
    #     topic   : pause_navigation
    #     timeout : 0.2
    #     # Higher priority than navigation so joystick & keyboard are not locked.
    #     priority: 45

