apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lvs.collector.fullname" . }}-telegraf
  labels:
    {{- include "lvs.collector.labels" . | nindent 4 }}
data:
  telegraf.conf: |
{{ .Values.telemetry.telegrafConfig | nindent 4 }}
