# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vital.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
"""Note: runtime_version validation removed for compatibility with protobuf 4.x.

The original generated code expected Protobuf Python 5.29.0 and imported
google.protobuf.runtime_version. To remain compatible with tensorflow-cpu
2.16.x (which requires protobuf<5), we skip this runtime version check.
"""
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvital.proto\x12\x05vital\x1a\x1bgoogle/protobuf/empty.proto\"\xea\x01\n\x05Vital\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x10\n\x08waveform\x18\x06 \x03(\x02\x12\x1d\n\x15waveform_frequency_hz\x18\x07 \x01(\x05\x12,\n\x08metadata\x18\x08 \x03(\x0b\x32\x1a.vital.Vital.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"1\n\rVitalResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2z\n\x0cVitalService\x12\x36\n\x0cStreamVitals\x12\x0c.vital.Vital\x1a\x16.google.protobuf.Empty(\x01\x12\x32\n\x0cPublishVital\x12\x0c.vital.Vital\x1a\x14.vital.VitalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vital_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VITAL_METADATAENTRY']._loaded_options = None
  _globals['_VITAL_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_VITAL']._serialized_start=52
  _globals['_VITAL']._serialized_end=286
  _globals['_VITAL_METADATAENTRY']._serialized_start=239
  _globals['_VITAL_METADATAENTRY']._serialized_end=286
  _globals['_VITALRESPONSE']._serialized_start=288
  _globals['_VITALRESPONSE']._serialized_end=337
  _globals['_VITALSERVICE']._serialized_start=339
  _globals['_VITALSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
