# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import vital_pb2 as vital__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vital_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VitalServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVitals = channel.stream_unary(
                '/vital.VitalService/StreamVitals',
                request_serializer=vital__pb2.Vital.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PublishVital = channel.unary_unary(
                '/vital.VitalService/PublishVital',
                request_serializer=vital__pb2.Vital.SerializeToString,
                response_deserializer=vital__pb2.VitalResponse.FromString,
                _registered_method=True)


class VitalServiceServicer(object):
    """Service definition
    """

    def StreamVitals(self, request_iterator, context):
        """Bidirectional streaming: services send vitals TO aggregator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishVital(self, request, context):
        """Alternative: request-response for single vitals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VitalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVitals': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamVitals,
                    request_deserializer=vital__pb2.Vital.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PublishVital': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishVital,
                    request_deserializer=vital__pb2.Vital.FromString,
                    response_serializer=vital__pb2.VitalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vital.VitalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vital.VitalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VitalService(object):
    """Service definition
    """

    @staticmethod
    def StreamVitals(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/vital.VitalService/StreamVitals',
            vital__pb2.Vital.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishVital(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vital.VitalService/PublishVital',
            vital__pb2.Vital.SerializeToString,
            vital__pb2.VitalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
