adbscan_sub_node:
  ros__parameters:
    Lidar_type: 2D
    Lidar_topic: scan
    Verbose: True
    subsample_ratio: 5.0
    x_filter_back: 4.0
    y_filter_left: 10.0
    y_filter_right: -20.0
    z_filter: -1.3
    Z_based_ground_removal: 1.0
    base: 2.24585885
    coeff_1: -0.350137
    coeff_2: -0.22432557
    scale_factor: 0.07
