# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0025
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 5

