# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions
# and limitations under the License.

"""docconf.py - common configuration for docs sites"""

# this file contains common configuration
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# pylint - sphinx doesn't use UPPER_CASE naming style for constants
# pylint: disable=invalid-name

import os
import sys
import pathlib
import glob
import re
import shutil

project = "Robotics AI Suite Documentation"

copyright = "2025, Intel Corporation"  # pylint: disable=redefined-builtin
author = "Intel Corporation"

version = "3.0"
release = version

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# strict mode - all warnings are errors
warning_is_error = True

# extensions
extensions = [
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_favicon",
    "sphinx_sitemap",
    "sphinxcontrib.asciinema",
    #    "sphinxcontrib.images",
    "sphinxcontrib.jquery",
    "sphinxcontrib.mermaid",
    "sphinxcontrib.openapi",
    "sphinxcontrib.spelling",
    "sphinxcontrib.video",
    "sphinx_tabs.tabs",
    "myst_parser",
    "breathe",
]

breathe_projects = {
    "rvc_control": "rvc/_assets/doxygen/rvc_control/xml/",
    "rvc_vision": "rvc/_assets/doxygen/rvc_vision/xml/",
}

templates_path = ["_templates"]

# exclude these files from processing
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "README.md",
]

# The suffix(es) of source filenames.
source_suffix = {".rst": "restructuredtext"}

# text encoding
source_encoding = "UTF-8"

# The language for content autogenerated by Sphinx.
language = "en"

# The master toctree document (entry point)
master_doc = "index"

# rst_epilog, added to the end of every rst doc
# include substituions in base directory
rst_epilog = """
.. include:: /substitutions.txt
"""

# Create empty dictionary
myst_substitutions = {}

# config for autosectionlabel
# see: https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html
autosectionlabel_prefix_document = True
autosectionlabel_maxdepth = 3

# list of words that shouldn't fail the spellchecker
spelling_word_list_filename = [
    "../dict.txt",
]

spelling_filters = ["sphinxcontrib.spelling.filters.ContractionFilter"]

spelling_exclude_patterns = [
    "release_notes/containers_helm_charts*",
    "release_notes/third_party_components*",
]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
html_title = "Robotics AI Suite Documentation"
# Conditionally use Spark Sphinx theme if available, fallback to PyData theme
try:
    import spark_sphinx_theme
except ImportError:
    html_theme = "pydata_sphinx_theme"
else:
    html_theme = "spark_sphinx_theme"

# these are specific to the spark_sphinx_theme
html_context = {
    "default_mode": "auto",
    "header_variant": "spark-color",
    "footer_variant": "simple",
    "content_width": "large",
    "color_scheme": "tb",
}
html_theme_options = {
    "navigation_depth": 3,
    "show_toc_level": 1,
    "show_nav_level": 1,
    # "collapse_navigation": False,
    # "navigation_with_keys": True,
    # Navbar Configuration
    # "navbar_start": [],  # Logo on the left
    "navbar_center": ["navbar-nav"],  # Main navigation in the center
    # "navbar_end": ["search-field"],  # Search + Theme Switcher on the right
    "header_links_before_dropdown": 4,
    "logo": {
        "text": "Robotics AI Suite",
        # "image_dark": "_static/logo-dark.svg",
    },
    "show_prev_next": False,
}
# Dynamically add switcher content if switcher_data.txt exists
switcher_data_file = os.path.dirname(os.path.abspath(__file__)) + "/switcher_data.txt"
if os.path.isfile(switcher_data_file):
    with open(switcher_data_file) as file:
        lines = [line.rstrip() for line in file]
    # Switcher URL needs to exist prior to building, so hardcode now and replace later
    html_theme_options_append = {
        "switcher": {
            "json_url": "https://docs.openedgeplatform.intel.com/theme/switcher.json",
            "version_match": f"{lines[1].split()[0]}",
        },
        "navbar_start": ["navbar-logo", "version-switcher"],
    }
    html_theme_options.update(html_theme_options_append)

# common theme options
html_baseurl = (
    "https://docs.openedgeplatform.intel.com/edge-ai-suites/robotics-ai-suite/"
)
html_favicon = "_static/logo.svg"
html_show_sourcelink = True  # Show source link
html_show_sphinx = False  # Hide "Built with Sphinx"
html_static_path = ["_static"]

# Linkcheck options
linkcheck_timeout = 5
linkcheck_retries = 4

linkcheck_ignore = [
    "https://www.intel.com/",
    "https://ark.intel.com/",
    "../static",  # ignore links to OpenAPI docs
]

# replacement user agent to avoid 403 errors
linkcheck_request_headers = {
    "*": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/134.0.0.0 Safari/537.36",
    }
}

linkcheck_exclude_documents = [
    "release_notes/containers_helm_charts*",
    "release_notes/third_party_components*",
]

myst_heading_anchors = 5
suppress_warnings = ["myst.xref_missing"]
myst_enable_extensions = [
    "attrs_inline",
    "attrs_block",
    "substitution",
    "colon_fence",
]


def show_hidden_directives(app, config):  # pylint: disable=unused-argument
    """
    Remove custom html comment tags used to hide the Sphinx directives in .md files
    """
    mdocs = pathlib.Path(__file__).parent
    mdfiles = glob.iglob(os.path.join(mdocs, "*/**/*.md"), recursive=True)
    for md in mdfiles:
        if os.path.isfile(md):
            try:
                with open(md, "r+", encoding="utf-8") as md_file:
                    contents = md_file.read()
                    start_tag = re.findall(r"<!--\s{0,2}hide.{0,2}directive", contents)
                    if start_tag:
                        # Remove the "<!--hide_directive" comment tag that hides content in GitHub.
                        rm_start_tag = [
                            (re.sub(r"<!--\s{0,2}hide.{0,2}directive", "", h))
                            for h in start_tag
                        ]
                        for a, b in zip(start_tag, rm_start_tag):
                            contents = contents.replace(a, b)
                        # Remove the "hide_directive-->" comment tag that hides content in GitHub.
                        end_tag = re.findall(r"hide.{0,2}directive\s{0,2}-->", contents)
                        rm_end_tag = [
                            (re.sub(r"hide.{0,2}directive\s{0,2}-->", "", i))
                            for i in end_tag
                        ]
                        for c, d in zip(end_tag, rm_end_tag):
                            contents = contents.replace(c, d)
                        md_file.seek(0)
                        md_file.write(contents)
                        md_file.truncate()
                        print("Uncommented directives in " + str(md))
            except Exception:  # pylint: disable=broad-exception-caught
                pass


def setup(app):
    """
    Sphinx entrypoint function
    """
    app.connect("config-inited", show_hidden_directives)
    app.add_css_file("robotics-custom.css")
    app.add_js_file("robotics-custom.js")
