# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

httpProxy: ""
httpsProxy: ""
noProxy: "localhost,127.0.0.0/8,10.0.0.0/8,127.0.0.1,0.0.0.0,172.16.0.0/12,192.168.0.0/16"

trafficIntersections:
  apiEndpoint: "/api/v1/traffic/current?images=false"
  # Add or remove entries based on available Traffic Intersection deployments.
  hosts:
    - "http://127.0.0.1:8081"
    - "http://127.0.0.1:8082"
