mqtt:
  enabled: true
  host: mqtt-broker
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

logger:
  default: info

detect:
  enabled: false

snapshots:
  enabled: false

record:
  enabled: true
  retain:
    days: 1
    mode: all

cameras:
  camera1:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:{RTSP_STREAM_PORT}/camera1
          input_args: preset-rtsp-generic
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -movflags +faststart
    detect:
      enabled: false
    motion:
      enabled: false
    snapshots:
      enabled: false
    record:
      enabled: true
      retain:
        days: 1
        mode: all

  camera2:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:{RTSP_STREAM_PORT}/camera2
          input_args: preset-rtsp-generic
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -movflags +faststart
    detect:
      enabled: false
    motion:
      enabled: false
    snapshots:
      enabled: false
    record:
      enabled: true
      retain:
        days: 1
        mode: all

  camera3:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:{RTSP_STREAM_PORT}/camera3
          input_args: preset-rtsp-generic
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -movflags +faststart
    detect:
      enabled: false
    motion:
      enabled: false
    snapshots:
      enabled: false
    record:
      enabled: true
      retain:
        days: 1
        mode: all

  camera4:
    ffmpeg:
      inputs:
        - path: rtsp://{RTSP_STREAM_IP}:{RTSP_STREAM_PORT}/camera4
          input_args: preset-rtsp-generic
          roles:
            - record
      output_args:
        record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -movflags +faststart
    detect:
      enabled: false
    motion:
      enabled: false
    snapshots:
      enabled: false
    record:
      enabled: true
      retain:
        days: 1
        mode: all

version: 0.15-1
