replicaCount: 1

imagePullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault

resources: {}

livenessProbe:
  tcpSocket:
    port: redis
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  tcpSocket:
    port: redis
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

startupProbe:
  tcpSocket:
    port: redis
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 60

images:
  redis: redis:7
