files: ^metro-ai-suite/smart-route-planning-agent/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: (^|/)charts?(/|$)
      - id: check-json
      - id: check-toml
      - id: debug-statements
      - id: check-merge-conflict
      - id: name-tests-test
        exclude: ^tests/fixtures/
        args: [ --pytest-test-first ]
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: no-commit-to-branch
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [types-pyyaml, types-requests]
        args: [ --ignore-missing-imports ]
        exclude: ^metro-ai-suite/smart-route-planning-agent/testing/resources/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        types_or: [ python, pyi ]
        args: [ --fix, --exit-non-zero-on-fix, --ignore-noqa ]
      - id: ruff-format
        types_or: [ python, pyi ]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.12
    hooks:
      - id: uv-sync
        args: ["--locked", "--all-packages"]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
        name: helmlint
        description: Run helm lint, a linter for helm charts
        entry: hooks/helmlint.sh
        language: script
        files: \.((ya?ml)|(tpl))$
        require_serial: true
