apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lvs.shared.fullname" . }}-credentials
  labels:
    {{- include "lvs.shared.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ required "global.credentials.minioRootUser is required" .Values.global.credentials.minioRootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ required "global.credentials.minioRootPassword is required" .Values.global.credentials.minioRootPassword | quote }}
  POSTGRES_USER: {{ required "global.credentials.postgresUser is required" .Values.global.credentials.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ required "global.credentials.postgresPassword is required" .Values.global.credentials.postgresPassword | quote }}
  MQTT_USER: {{ required "global.credentials.mqttUser is required" .Values.global.credentials.mqttUser | quote }}
  MQTT_PASSWORD: {{ required "global.credentials.mqttPassword is required" .Values.global.credentials.mqttPassword | quote }}
