# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
adbscan_sub_node:
  ros__parameters:
    Lidar_type: RS
    Lidar_topic: /camera/depth/color/points
    Verbose: False
    subsample_ratio: 500.0
    x_filter_back: 4.0
    y_filter_left: 10.0
    y_filter_right: -20.0
    z_filter: -1.3
    Z_based_ground_removal: 1.0
    base: 3.4694
    coeff_1: -0.0335
    coeff_2: 0.00015124
    scale_factor: 0.9
