apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  labels:
    {{- include "lvs.mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    app: mqtt-broker
