# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

all: dbscan

dbscan: main.cpp dbscan_adaptiveK.cpp Util.cpp
	g++ -o dbscan main.cpp dbscan_adaptiveK.cpp Util.cpp

