# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
gesture_recognizer_node:
  ros__parameters:
    Camera_topic: /camera/color/image_raw
    simulated_camera_topic: /sim_camera
    Verbose: True
    use_sim_time: False