# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\x04pose\"\x1f\n\x07Joint2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"*\n\x07Joint3D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"w\n\nPersonPose\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12 \n\tjoints_2d\x18\x02 \x03(\x0b\x32\r.pose.Joint2D\x12 \n\tjoints_3d\x18\x03 \x03(\x0b\x32\r.pose.Joint3D\x12\x12\n\nconfidence\x18\x04 \x03(\x02\"\x80\x01\n\tPoseFrame\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x03\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12 \n\x06people\x18\x03 \x03(\x0b\x32\x10.pose.PersonPose\x12\x12\n\nframe_data\x18\x04 \x01(\x0c\x12\x14\n\x0c\x66rame_number\x18\x05 \x01(\x05\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2h\n\x0bPoseService\x12)\n\x0bPublishPose\x12\x0f.pose.PoseFrame\x1a\t.pose.Ack\x12.\n\x0eStreamPoseData\x12\x0f.pose.PoseFrame\x1a\t.pose.Ack(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINT2D']._serialized_start=20
  _globals['_JOINT2D']._serialized_end=51
  _globals['_JOINT3D']._serialized_start=53
  _globals['_JOINT3D']._serialized_end=95
  _globals['_PERSONPOSE']._serialized_start=97
  _globals['_PERSONPOSE']._serialized_end=216
  _globals['_POSEFRAME']._serialized_start=219
  _globals['_POSEFRAME']._serialized_end=347
  _globals['_ACK']._serialized_start=349
  _globals['_ACK']._serialized_end=383
  _globals['_POSESERVICE']._serialized_start=385
  _globals['_POSESERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
