apiVersion: batch/v1
kind: Job
metadata:
  name: assets-prep
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: assets
          image: "{{ .Values.assets.image.repository }}/{{ .Values.assets.image.name }}:{{ .Values.assets.image.tag }}"
          imagePullPolicy: {{ .Values.assets.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: device-config
          env:
            {{- if .Values.http_proxy }}
            - name: HTTP_PROXY
              value: {{ .Values.http_proxy | quote }}
            - name: http_proxy
              value: {{ .Values.http_proxy | quote }}
            {{- end }}
            {{- if .Values.https_proxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.https_proxy | quote }}
            - name: https_proxy
              value: {{ .Values.https_proxy | quote }}
            {{- end }}
            {{- if .Values.no_proxy }}
            - name: NO_PROXY
              value: {{ .Values.no_proxy | quote }}
            - name: no_proxy
              value: {{ .Values.no_proxy | quote }}
            {{- end }}
          volumeMounts:
            - name: models
              mountPath: /models
            - name: videos
              mountPath: /videos
            - name: model-config
              mountPath: /app/configs
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models-pvc
        - name: videos
          persistentVolumeClaim:
            claimName: videos-pvc
        - name: model-config
          configMap:
            name: rppg-model-config