apiVersion: v1
kind: ConfigMap
metadata:
  name: rppg-model-config
data:
  model-config.yaml: |-
    ai-ecg:
      models:
        - name: hubert_ecg_small_fp16
          type: ai-ecg
          hub: hf
          source: hubert-ecg
          source_dir: /models/downloads/ai-ecg/hubert-ecg-small
          target_dir: /models/ai-ecg
          ir_file: hubert_ecg_small_fp16.xml
          video_dir: /videos/ai-ecg

    rppg:
      models:
        - name: mtts_can.hdf5
          type: rppg
          hub: hls
          source_model_path: /models/downloads/rppg/mtts_can.hdf5
          target_dir: /models/rppg
          model_file: mtts_can.hdf5
          video_dir: /videos/rppg
          video_url: https://github.com/opencv/opencv/raw/master/samples/data/vtest.avi

    pose-3d:
      models:
        - name: human-pose-estimation-3d-0001
          type: 3d-pose
          hub: hls
          source_archive_path: /models/downloads/3d-pose/human-pose-estimation-3d.tar.gz
          target_dir: /models/3d-pose
          ir_file: human-pose-estimation-3d-0001.xml
          video_dir: /videos/3d-pose
          video_url: https://www.pexels.com/download/video/6130537
