{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-modal-patient-monitoring-pose-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/chunked-transfer-encoding: "on"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: multi-modal-patient-monitoring.local
      http:
        paths:
          - path: /video_feed
            pathType: Exact
            backend:
              service:
                name: pose
                port:
                  number: 8085

          - path: /pose-video
            pathType: Exact
            backend:
              service:
                name: pose
                port:
                  number: 8085
{{- end }}