apiVersion: v1
kind: ConfigMap
metadata:
  name: vdms-vector-db-config
  labels:
    {{- include "lvs.vdmsdb.labels" . | nindent 4 }}
data:
  OVERRIDE_db_root_path: /db
  OVERRIDE_images_path: /db/images
  OVERRIDE_descriptors_path: /db/descriptors
  OVERRIDE_blobs_path: /db/blobs
  OVERRIDE_pmgd_path: /db/graph
