{{/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.vlmServing.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stia.vlmServing.fullname" . }}-models
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: vlm-serving
  {{- if .Values.vlmServing.persistence.keepOnUninstall }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vlmServing.persistence.size }}
  {{- if .Values.vlmServing.persistence.storageClass }}
  storageClassName: {{ .Values.vlmServing.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- if .Values.trafficAgent.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stia.trafficAgent.fullname" . }}-data
  labels:
    {{- include "stia.labels" . | nindent 4 }}
    app.kubernetes.io/component: traffic-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.trafficAgent.persistence.size }}
  {{- if .Values.trafficAgent.persistence.storageClass }}
  storageClassName: {{ .Values.trafficAgent.persistence.storageClass }}
  {{- end }}
{{- end }}
