{{/*
Copyright (C) 2025 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if and .Values.tls.caCert (not .Values.tls.caCertSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stia.fullname" . }}-ca-cert
  labels:
    {{- include "stia.labels" . | nindent 4 }}
type: Opaque
data:
  scenescape-ca.pem: {{ .Values.tls.caCert | b64enc | quote }}
{{- end }}
{{- if .Values.vlmServing.huggingfaceToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stia.fullname" . }}-hf-token
  labels:
    {{- include "stia.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.vlmServing.huggingfaceToken | b64enc | quote }}
{{- end }}
