# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2025 Intel Corporation
ur_manipulator:
    #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    #kinematics_solver: bio_ik/BioIKKinematicsPlugin
    kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    #kinematics_solver: pick_ik/PickIkPlugin
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.005
    kinematics_solver_attempts: 1.0
    #mode: gd_c
