{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-service.fullname" . }}
  labels:
    {{- include "metrics-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics-service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "metrics-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: prometheus
      port: 9273
      targetPort: prometheus
      protocol: TCP
