{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-route-planning-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "smart-route-planning-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPortName }}
      protocol: TCP
  selector:
    {{- include "smart-route-planning-agent.selectorLabels" . | nindent 4 }}
