apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-influxdb-pv
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"  # Required by Helm
  annotations:
    meta.helm.sh/release-name: "smart-intersection"  # Required by Helm
    meta.helm.sh/release-namespace: "smart-intersection"  # Required by Helm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /mnt/data/influxdb  # Replace with a valid path on your node