namespace: ""
replicaCount: 1
http_proxy:
https_proxy: 
no_proxy: "localhost,127.0.0.1,.svc,.cluster.local"
 
 
persistence:
  size: 20Gi
  # For local-path-provisioner and most single-node setups, use ReadWriteOnce.
  accessMode: ReadWriteOnce
  # Leave empty to use the cluster default StorageClass.
  storageClassName: ""
 
# Shared PVCs for models and videos
models:
  enabled: true
  mountPath: /models
  claimName: models-pvc
 
videos:
  enabled: true
  mountPath: /videos
  claimName: videos-pvc
 
service:
  type: ClusterIP
 
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/chunked-transfer-encoding: "on"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: multi-modal-patient-monitoring.local
      paths:
        # Aggregator API
        - path: /video-stream(/|$)(.*)
          pathType: ImplementationSpecific
          service: aggregator
          port: 80
        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          service: aggregator
          port: 80
        # Frontend UI
        - path: /()(.*)
          pathType: ImplementationSpecific
          service: ui
          port: 80
  tls: []
 
# Images
ui:
  image:
    repository: intel
    name: hl-ai-ui
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
aggregator:
  image:
    repository: intel
    name: hl-ai-patient-monitoring-aggregator
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
aiEcg:
  image:
    repository: intel
    name: hl-ai-ecg
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
rppg:
  image:
    repository: intel
    name: hl-ai-rppg
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
pose:
  image:
    repository: intel
    name: hl-ai-3dpose
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
metrics:
  image:
    repository: intel
    name: hl-ai-metrics-collector
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
ddsBridge:
  image:
    repository: intel
    name: hl-ai-dds-bridge
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
mdpnp:
  image:
    repository: intel
    name: hl-ai-mdpnp
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
assets:
  image:
    repository: intel
    name: hl-ai-patient-monitoring-assets
    tag: "2026.0.0"
    pullPolicy: IfNotPresent
 
# Devices
devices:
  ECG_DEVICE: "GPU"
  RPPG_DEVICE: "GPU"
  MDPNP_DEVICE: "CPU"
  POSE_3D_DEVICE: "GPU"