persistence:
  size: 20Gi

service:
  type: ClusterIP

ingress:
  enabled: true
  className: nginx

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/chunked-transfer-encoding: "on"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"

  hosts:
    - host: multi-modal-patient-monitoring.local
      paths:
        - path: /video-stream(/|$)(.*)
          pathType: ImplementationSpecific
          service: aggregator
          port: 8001

        - path: /api(/|$)(.*)
          pathType: ImplementationSpecific
          service: aggregator
          port: 8001

        - path: /()(.*)
          pathType: ImplementationSpecific
          service: ui
          port: 80

  tls: []


ui:
  image:
    repository: intel
    name: hl-ai-ui
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

aggregator:
  image:
    repository: intel
    name: hl-ai-patient-monitoring-aggregator
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

aiEcg:
  image:
    repository: intel
    name: hl-ai-ecg
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

rppg:
  image:
    repository: intel
    name: hl-ai-rppg
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

pose:
  image:
    repository: intel
    name: hl-ai-3dpose
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

metrics:
  image:
    repository: intel
    name: hl-ai-metrics-collector
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

ddsBridge:
  image:
    repository: intel
    name: hl-ai-dds-bridge
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

mdpnp:
  image:
    repository: intel
    name: hl-ai-mdpnp
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

assets:
  image:
    repository: intel
    name: hl-ai-patient-monitoring-assets
    tag: "2026.0-rc1"
    pullPolicy: IfNotPresent

devices:
  ECG_DEVICE: "GPU"
  RPPG_DEVICE: "GPU"
  MDPNP_DEVICE: "CPU"
  POSE_3D_DEVICE: "GPU"
